package web

func init() {
	pairs := map[string][2]string{
		"ui.oss_history":                               {"历史 OSS Insight 排名", "Historical OSS Insight ranks"},
		"category_description.coding-agents":           {"帮助开发者编写、审查、调试和维护代码。", "Assist with writing, reviewing, debugging, and maintaining code."},
		"category_description.research-agents":         {"自主检索资料、分析来源并完成研究任务。", "Search sources, investigate questions, and produce research."},
		"category_description.browser-computer-agents": {"通过浏览器或桌面界面操作软件和完成任务。", "Operate websites, browsers, and desktop applications."},
		"category_description.workflow-agents":         {"将个人任务和业务流程组织成可重复运行的自动化。", "Automate personal tasks and repeatable business workflows."},
		"category_description.agent-platforms":         {"构建、运行、协调和管理一个或多个 Agent。", "Build, run, coordinate, and supervise agents."},
		"category_description.ai-infrastructure":       {"为 Agent 提供模型、记忆、工具、运行环境和评测能力。", "Models, memory, tools, runtimes, and evaluation for agents."},
		"category_description.ai-agent":                {"通用型 Agent，以及尚未确认细分用途的项目。", "General-purpose agents and projects awaiting a more specific type."},
		"ui.category_library":                          {"浏览项目", "Browse projects"},
		"ui.category_rules":                            {"关于自动分类", "About classification"},
		"ui.category_rules_help":                       {"项目可以属于多个类型。自动分类根据项目描述和 GitHub 标签给出，可通过手动添加时选择分类进行确认；证据不足的项目保留为待分类。分类覆盖率不代表整个 GitHub 社区的覆盖率。", "Projects may belong to several types. Automatic suggestions use descriptions and GitHub topics; a manual choice takes precedence. Unclear projects remain unclassified. Coverage refers to this library, not all of GitHub."},
		"ui.category_metrics":                          {"查看分类的增长数据", "View category growth data"},
		"ui.read_readme":                               {"阅读项目 README", "Read the project README"},
		"ui.watch_reason":                              {"关注原因：", "Why follow: "},
		"category.multi-agent":                         {"多 Agent 协作", "Multi-agent"},
		"category.workbench":                           {"Agent 工作台", "Workbench"},
		"category.client-and-remote-access":            {"客户端与远程访问", "Clients & remote access"},
		"category.skills":                              {"Skills 与可复用能力", "Skills"},
		"category.harness":                             {"运行框架 / Harness", "Harness"},
		"category.memory":                              {"记忆与上下文", "Memory"},
		"category.browser-and-tools":                   {"工具与连接器", "Tools & connectors"},
		"category.reliability":                         {"评测与可靠性", "Reliability"},
		"nav.dashboard":                                {"趋势看板", "Trends"},
		"nav.repositories":                             {"GitHub 项目", "GitHub projects"},
		"nav.discoveries":                              {"每日发现", "Discover"},
		"nav.topics":                                   {"Agent 分类", "Categories"},
		"ui.brand_note":                                {"开源趋势观察", "independent GitHub trends tracker"},
		"ui.workspace":                                 {"工作区", "WORKSPACE"},
		"ui.my_watchlist":                              {"我的关注", "My watchlist"},
		"ui.add_project":                               {"添加关注", "Add project"},
		"ui.source_note":                               {"从 Trending 发现，持续观察 Star", "Discover on Trending. Follow daily stars."},
		"ui.observation_workspace":                     {"开源观察", "Observatory"},
		"ui.data_date":                                 {"数据日期 %s", "Data as of %s"},
		"ui.stale_notice":                              {"当前数据停留在 %s，近期走势尚未采集。", "Data stops at %s. Recent movement has not been collected."},
		"ui.inspect_collection":                        {"查看采集记录", "Collection history"},
		"ui.dashboard_title":                           {"开源项目，持续关注", "Follow what happens next."},
		"ui.dashboard_description":                     {"从每日发现到持续增长，看清值得关注的项目与方向。", "See which projects are gaining attention, holding steady, or losing momentum."},
		"ui.view_date":                                 {"查看", "View"},
		"ui.category_filter":                           {"按 Agent 类型筛选", "Filter by agent type"},
		"ui.window_summary":                            {"所选周期变化", "Selected period"},
		"ui.up_projects":                               {"持续增长", "Gaining stars"},
		"ui.up_note":                                   {"所选周期 Star 净增长的项目", "Positive Star change in this period"},
		"ui.flat_projects":                             {"增长持平", "Holding steady"},
		"ui.flat_note":                                 {"有完整对比，Star 数未变化", "Observed at both dates, no Star change"},
		"ui.slowdown":                                  {"势头回落", "Losing momentum"},
		"ui.slowdown_note":                             {"在 %s 个可对比前后周期的项目中", "Among %s projects with two comparable windows"},
		"ui.new_today":                                 {"当天新入库", "New to the radar"},
		"ui.new_note":                                  {"首次进入我们的观察范围", "First discovered on the selected date"},
		"ui.view_discoveries":                          {"查看每日发现", "View daily discoveries"},
		"ui.only_new_on_date":                          {"仅看当天新入库", "New on this date only"},
		"ui.new_filter_help":                           {"仅显示在所选观测日期首次入库的项目，入库日期不等于 GitHub 创建日期。", "Only projects first added on the observation date. This is not their GitHub creation date."},
		"ui.chart_title":                               {"关注度走势", "Attention over time"},
		"ui.chart_subtitle":                            {"同一批 %s 个项目 · 起点 = 100", "Same cohort of %s projects · starts at 100"},
		"ui.chart_help":                                {"这条曲线比较同一批项目，起点设为 100。仅使用起止两天都有成功观测的项目；中间缺少观测时保留断点。项目库新增数量不会直接抬高这条曲线。", "The same projects are compared throughout, normalized to 100 at the start. Both endpoints must have successful observations. Incomplete days remain gaps; new additions do not inflate the curve."},
		"ui.no_trend":                                  {"这个周期还没有完整走势", "Waiting for comparable history"},
		"ui.no_trend_help":                             {"换一个日期或缩短周期，也可以先查看每日发现。", "Try another date or a shorter period, or explore the latest discoveries."},
		"ui.chart_method":                              {"图表口径与精确数值", "Method and exact values"},
		"ui.index":                                     {"关注度指数", "Attention index"},
		"ui.direction_title":                           {"项目表现分布", "How projects are moving"},
		"ui.direction_help":                            {"只统计有完整周期对比的项目", "Projects with valid observations at both dates"},
		"ui.direction_aria":                            {"增长 %s 个、持平 %s 个、减少 %s 个", "%s growing, %s steady, %s declining"},
		"ui.comparable":                                {"可比项目", "comparable projects"},
		"ui.growing":                                   {"Star 增长", "Gaining stars"},
		"ui.flat":                                      {"Star 持平", "Unchanged"},
		"ui.declining":                                 {"Star 减少", "Losing stars"},
		"ui.coverage_note":                             {"当日已采集 %s / %s 个项目", "%s / %s projects observed at the endpoint"},
		"ui.watch_movement":                            {"值得留意的变化", "Movements to watch"},
		"ui.comparison_dates":                          {"%s 至 %s · 按真实 Star 变化比较", "%s to %s · real Star observations"},
		"ui.all_projects":                              {"查看全部项目", "All projects"},
		"ui.fastest":                                   {"涨得最快", "Fastest growth"},
		"ui.fastest_help":                              {"按本周期 Star 增量排序", "Largest Star gains in this period"},
		"ui.slowest":                                   {"增长平缓", "Slowest growth"},
		"ui.slowest_help":                              {"从零增长到最小正增长", "Zero change and the smallest positive gains"},
		"ui.slowdown_help":                             {"前后两个周期，增速正在下降", "Slower gains than the preceding period"},
		"ui.no_board_data":                             {"暂无符合条件的可比项目", "No comparable projects in this group"},
		"ui.methodology":                               {"如何理解这些变化", "How to read these signals"},
		"ui.methodology_help":                          {"涨得最快按所选周期增量排序；增长平缓包括零增长和较小的正增长；势头回落要求前后两个等长周期都有数据。Star 减少与增速回落是两回事，缺失数据也不等于零增长。排名变化仅指当前观察样本内的相对位置。", "Fastest and slowest use the selected period's Star change. Losing momentum compares two equal windows. Losing stars, slowing growth, and missing observations are distinct states. Ranks refer only to the monitored sample."},
		"ui.slowdown_window":                           {"减速对比：%s → %s → %s", "Momentum comparison: %s → %s → %s"},
		"category.":                                    {"全部类型", "All types"},
		"category.coding-agents":                       {"编程助手", "Coding"},
		"category.research-agents":                     {"研究与检索", "Research"},
		"category.browser-computer-agents":             {"浏览器与电脑操作", "Computer use"},
		"category.workflow-agents":                     {"工作流与自动化", "Workflows"},
		"category.agent-platforms":                     {"构建与协作平台", "Agent platforms"},
		"category.ai-infrastructure":                   {"AI 基础设施", "Infrastructure"},
		"category.ai-agent":                            {"通用 Agent", "General agents"},
		"category.__unclassified":                      {"待分类", "Unclassified"},
		"ui.discovery_title":                           {"每天，都有新发现", "A new day. New discoveries."},
		"ui.discovery_description":                     {"查看首次进入雷达的项目，了解它们做什么，继续追踪后续发展。", "Meet projects entering the radar and follow what they do next."},
		"ui.discovery_explanation":                     {"新入库不等于刚创建。这里按首次发现日期归档；发现的项目会自动进入项目库持续跟踪。", "New to the radar does not mean newly created. Discoveries enter the project library automatically for ongoing monitoring."},
		"ui.discovered_on":                             {"入库日期", "Discovery date"},
		"ui.created_on":                                {"创建于", "Created"},
		"ui.auto_tracking":                             {"已入库 · 持续观测", "In library · monitoring"},
		"ui.details":                                   {"了解项目", "Project details"},
		"ui.no_discoveries":                            {"这一天还没有新项目", "No discoveries on this date"},
		"ui.no_discoveries_help":                       {"切换日期查看历史发现，或添加你感兴趣的 GitHub 项目。", "Choose another date or add a GitHub project you want to follow."},
		"ui.first_page":                                {"返回第一页", "Back to first page"},
		"ui.all_library":                               {"全部项目", "All projects"},
		"ui.search_hint":                               {"搜索项目名或描述…", "Search projects or descriptions…"},
		"ui.filter":                                    {"筛选", "Filter"},
		"ui.pending":                                   {"待采集", "Awaiting observation"},
		"ui.last_observed":                             {"上次观测 %s", "Last observed %s"},
		"ui.no_description":                            {"这个项目暂未提供描述，可打开 GitHub 查看 README。", "No description is available. Open GitHub to read the README."},
		"ui.library_note":                              {"%s 个项目 · %s 个有本周期对比", "%s projects · %s comparable this period"},
		"ui.period_gain":                               {"周期增长", "Period gain"},
		"ui.about_project":                             {"这个项目做什么", "About this project"},
		"ui.github_description":                        {"项目原始描述", "Repository description"},
		"ui.analysis_available":                        {"研究解读", "Research notes"},
		"ui.analysis_empty":                            {"暂未添加进一步解读", "Further research has not been added yet"},
		"ui.created_unknown":                           {"创建时间未知", "Creation date unavailable"},
		"meta.repositories.title":                      {"项目库", "Project library"},
		"meta.repositories.description":                {"从第一次发现开始，持续追踪每一个项目。", "Every project, followed from its first discovery."},
		"meta.topics.title":                            {"Agent 分类", "Agent categories"},
		"meta.topics.description":                      {"按用途和能力理解项目，找到你想持续关注的方向。", "Explore projects by their purpose, capabilities, and technical direction."},
		"repositories.sort_newest":                     {"最近入库", "Recently discovered"},
		"repositories.sort_low_growth":                 {"增长平缓", "Slowest growth"},
		"repositories.sort_slowdown":                   {"势头回落", "Losing momentum"},
		"page.footer":                                  {"GitHub Trending 发现，Search 补充，Star 持续观察。", "Discover via GitHub Trending, supplement with Search, and follow daily stars."},
	}
	for key, pair := range pairs {
		messageCatalog[localeChinese][key] = pair[0]
		messageCatalog[localeEnglish][key] = pair[1]
	}
}
